/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EventOrgRole;


import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Event.Event;
import Business.Event.EventDirectory;
import Business.Network.Network;

import Business.Enterprise.Enterprise;
import Business.Event.Event;
import Business.Event.EventDirectory;

import Business.Organization.DoctorOrganization;
import Business.Organization.EventManagementOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EventCreateWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import UserInterface.DoctorRole.DoctorWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class RequestEventJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EventManagementOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EventDirectory eventDirectory;

    private EcoSystem business;

    
    public RequestEventJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EventManagementOrganization organization, EcoSystem business) {

        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;
        eventDirectory = new EventDirectory();
        popOrganizationComboBoxT3();
        comboOrg.setSelectedIndex(-1);
        txtBudget.setVisible(false);
        txtDoctors.setVisible(false);
        lblBudget.setVisible(false);
        lblDoc.setVisible(false);
        txtBudget.setText("0");
        txtDoctors.setText("0");
        eventDirectory = new EventDirectory();
        popOrganizationComboBoxT3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEventName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spinParticipationNo = new javax.swing.JSpinner();
        lblBudget = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        dateChooserEventDate = new com.toedter.calendar.JDateChooser();
        comboOrg = new javax.swing.JComboBox();
        lblOrganization = new javax.swing.JLabel();
        lblDoc = new javax.swing.JLabel();
        txtDoctors = new javax.swing.JTextField();
        btnAdditional = new javax.swing.JButton();
        pnlMyWorkSpaceBody = new javax.swing.JPanel();
        txtPersonalHeader2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Event Name:");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Event Date:");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);

        txtEventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEventNameActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Location");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Expected Participation:");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);

        lblBudget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBudget.setText("Expected Budget:");
        lblBudget.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblBudget.setOpaque(true);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        comboOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblOrganization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrganization.setText("Assign to organization:");
        lblOrganization.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblOrganization.setOpaque(true);

        lblDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoc.setText("No of doctors required:");
        lblDoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblDoc.setOpaque(true);

        btnAdditional.setText("Enter Additional details");
        btnAdditional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdditionalActionPerformed(evt);
            }
        });

        pnlMyWorkSpaceBody.setBackground(new java.awt.Color(102, 102, 102));
        pnlMyWorkSpaceBody.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMyWorkSpaceBody.setForeground(new java.awt.Color(255, 255, 255));

        txtPersonalHeader2.setForeground(new java.awt.Color(255, 255, 255));
        txtPersonalHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPersonalHeader2.setText("Process Work Request - Event Management ");

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMyWorkSpaceBodyLayout = new javax.swing.GroupLayout(pnlMyWorkSpaceBody);
        pnlMyWorkSpaceBody.setLayout(pnlMyWorkSpaceBodyLayout);
        pnlMyWorkSpaceBodyLayout.setHorizontalGroup(
            pnlMyWorkSpaceBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyWorkSpaceBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPersonalHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE))
        );
        pnlMyWorkSpaceBodyLayout.setVerticalGroup(
            pnlMyWorkSpaceBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyWorkSpaceBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtPersonalHeader2)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMyWorkSpaceBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblOrganization)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEventName)
                                    .addComponent(txtLocation)
                                    .addComponent(spinParticipationNo)
                                    .addComponent(dateChooserEventDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnAdditional))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(btnSubmit)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(pnlMyWorkSpaceBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dateChooserEventDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinParticipationNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganization)
                    .addComponent(comboOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdditional)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoc)
                    .addComponent(txtDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBudget)
                    .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnSubmit)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void popOrganizationComboBoxT3() {
        comboOrg.removeAllItems();

        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise.getEnterpriseType().getValue().contains("NGO") || enterprise.getEnterpriseType().getValue().contains("Hospital")) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization.getName().contains("Finance") || organization.getName().contains("HospitalAdminAssistant")) {
                            comboOrg.addItem(organization);
                        }

                    }
                }
            }
        }


    }



    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAddit;

    private void comboOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOrgActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EventOrgWorkAreaJPanel eowjp = (EventOrgWorkAreaJPanel) component;
        eowjp.populateRequestTable();
        eowjp.populateHistoryTable();
        eowjp.populateUpComingTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Date today = new Date();
        if (txtEventName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter event name", "Error", JOptionPane.ERROR_MESSAGE);

        } else if (dateChooserEventDate.getDate().before(today)) {

            JOptionPane.showMessageDialog(this, "Event date should be a future date", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (txtLocation.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter location", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (String.valueOf(spinParticipationNo.getValue()).equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the expected participation", "Error", JOptionPane.ERROR_MESSAGE);
        } else if ((Integer) spinParticipationNo.getValue() <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter the valid expected participation", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (txtBudget.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter budget", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (comboOrg.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please selected the organization to whom request is to assigned", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String eventName = txtEventName.getText();
            String location = txtLocation.getText();
            double budget = Double.parseDouble(txtBudget.getText());
            int noOfPpl = (Integer) spinParticipationNo.getValue();

            Date eventDate = dateChooserEventDate.getDate();

            Event e = new Event();
            e.setEventName(eventName);
            e.setLocation(location);
            e.setEventDate(eventDate);
            e.setNoOfPpl(noOfPpl);
            e.setBudget(budget);

            Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("h:mm:ss a");
            String formattedDate = sdf.format(date);

            EventCreateWorkRequest request = new EventCreateWorkRequest();
            request.setRequestDate(formattedDate);
            request.setRequestedby(userAccount);
            request.setEventName(eventName);
            request.setEventDate(eventDate);
            request.setRequestedOn(date);
            
            request.setEventLocation(location);
            request.setNoOfPpl(noOfPpl);

            request.setSender(userAccount);
            request.setOrganizationName(comboOrg.getSelectedItem().toString());
            if(comboOrg.getSelectedItem().toString().contains("HospitalAdminAssistant")){
                request.setDescription(eventName + " event at " + location + " and the required number of doctors is" + txtDoctors.getText());
                request.setNoOfDoctors(Integer.parseInt(txtDoctors.getText()));
                request.setBudget(0);

            }
            else{
                request.setDescription(eventName + " event at " + location + " and the required budget is" + budget);
                request.setNoOfDoctors(0);
                request.setDebit(budget);
                request.setNarration("Event Budget");
                request.setChequeNo("Budget released in Cash ");
                
            }

            request.setStatus("Sent");
            request.setReqByorganizationName(organization.getName());
            //enterprise.getWorkQueue().getWorkRequestList().add(request);

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof EventManagementOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                //org.getWorkQueue().getWorkRequestList().add(request);
                //userAccount.getWorkQueue().getWorkRequestList().add(request);
                organization.getEventList().add(e);

                enterprise.getWorkQueue().getWorkRequestList().add(request);

                JOptionPane.showMessageDialog(null, "Request Sent Successfully");
            }

        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventNameActionPerformed

    private void btnAdditionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdditionalActionPerformed
        if(comboOrg.getSelectedItem().toString().contains("HospitalAdminAssistant")){
            txtDoctors.setVisible(true);
            lblDoc.setVisible(true);
            txtBudget.setVisible(false);
            lblBudget.setVisible(false);

        }
        else if(comboOrg.getSelectedItem().toString().contains("Finance")){
            txtDoctors.setVisible(false);
            lblDoc.setVisible(false);
            txtBudget.setVisible(true);
            lblBudget.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select organization", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdditionalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdditional;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboOrg;
    private com.toedter.calendar.JDateChooser dateChooserEventDate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblDoc;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JPanel pnlMyWorkSpaceBody;
    private javax.swing.JSpinner spinParticipationNo;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtDoctors;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JLabel txtPersonalHeader2;
    // End of variables declaration//GEN-END:variables
}
