/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DataTeamRole;


import Business.Data.HomelessData;
import Business.Enterprise.Enterprise;
import Business.Organization.DatateamOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MyPC1
 */
public class AddDataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDataJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DatateamOrganization organization;
    private HomelessData h;
    public AddDataJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,DatateamOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.organization = organization;
        h=new HomelessData();
        Date date=new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("h:mm:ss a");
        String formattedDate = sdf.format(date);
        txtTime.setText(formattedDate);
        txtModified.setText(userAccount.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workRequestPanel = new javax.swing.JPanel();
        txtModified = new javax.swing.JTextField();
        lblTimestamp = new javax.swing.JLabel();
        lblCreated = new javax.swing.JLabel();
        txtFamilies = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        lblAgeGroup = new javax.swing.JLabel();
        txtCount = new javax.swing.JTextField();
        lblDisease = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        lblReason = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        lblFamilies = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtDisease = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        spinAge = new javax.swing.JSpinner();
        spinAgeTo = new javax.swing.JSpinner();
        lblTo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestPanel.setBackground(new java.awt.Color(255, 255, 255));
        workRequestPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        workRequestPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtModified.setEditable(false);
        txtModified.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        workRequestPanel.add(txtModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 294, 315, -1));

        lblTimestamp.setBackground(new java.awt.Color(204, 204, 204));
        lblTimestamp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimestamp.setText("Timestamp:");
        lblTimestamp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTimestamp.setOpaque(true);
        workRequestPanel.add(lblTimestamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 254, 206, -1));

        lblCreated.setBackground(new java.awt.Color(204, 204, 204));
        lblCreated.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreated.setText("Created by:");
        lblCreated.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblCreated.setOpaque(true);
        workRequestPanel.add(lblCreated, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 294, 206, -1));

        txtFamilies.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        workRequestPanel.add(txtFamilies, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 214, 315, -1));

        txtLocation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        workRequestPanel.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 13, 314, -1));

        lblAgeGroup.setBackground(new java.awt.Color(204, 204, 204));
        lblAgeGroup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgeGroup.setText("Age group:");
        lblAgeGroup.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAgeGroup.setOpaque(true);
        workRequestPanel.add(lblAgeGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 129, 206, -1));

        txtCount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        workRequestPanel.add(txtCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 87, 315, -1));

        lblDisease.setBackground(new java.awt.Color(204, 204, 204));
        lblDisease.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisease.setText("Chronic diseases:");
        lblDisease.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblDisease.setOpaque(true);
        workRequestPanel.add(lblDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 174, 206, -1));

        lblCount.setBackground(new java.awt.Color(204, 204, 204));
        lblCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCount.setText("No of people:");
        lblCount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblCount.setOpaque(true);
        workRequestPanel.add(lblCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 87, 206, -1));

        lblReason.setBackground(new java.awt.Color(204, 204, 204));
        lblReason.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReason.setText("Major reason for homelessness:");
        lblReason.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblReason.setOpaque(true);
        workRequestPanel.add(lblReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 47, -1, -1));

        txtReason.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        workRequestPanel.add(txtReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 47, 314, -1));

        lblFamilies.setBackground(new java.awt.Color(204, 204, 204));
        lblFamilies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFamilies.setText("No of families:");
        lblFamilies.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblFamilies.setOpaque(true);
        workRequestPanel.add(lblFamilies, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 214, 206, -1));

        lblLocation.setBackground(new java.awt.Color(204, 204, 204));
        lblLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLocation.setText("Location:");
        lblLocation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblLocation.setOpaque(true);
        workRequestPanel.add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 13, 206, -1));

        txtDisease.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        workRequestPanel.add(txtDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 174, 315, -1));

        txtTime.setEditable(false);
        txtTime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        workRequestPanel.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 254, 315, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        workRequestPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 334, -1, -1));

        spinAge.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        workRequestPanel.add(spinAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 124, 48, -1));

        spinAgeTo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        workRequestPanel.add(spinAgeTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 124, 53, -1));

        lblTo.setText("To");
        workRequestPanel.add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 132, 12, -1));

        add(workRequestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 121, 938, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Add Data");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(validation()){
        h.setLocation(txtLocation.getText());
        h.setReason(txtReason.getText());
        h.setNoOfPeople(Integer.parseInt(txtCount.getText()));
        h.setAgeGroup(spinAge.getValue().toString()+" - "+spinAgeTo.getValue().toString()   );
        h.setDiseases(txtDisease.getText());
        h.setNoOfFamilies(Integer.parseInt(txtFamilies.getText()));
        h.setTimeStamp((txtTime.getText()));
        h.setCreatedBy(txtModified.getText());
        organization.getHomelessDataList().add(h);
        
        if(Integer.parseInt(txtCount.getText())>=30 || (Integer.parseInt(txtFamilies.getText())>=10)){
            JOptionPane.showMessageDialog(this, "Please raise a work request to Event management team to reduce "+txtReason.getText()+"  at location "+txtLocation.getText()+" due to the high count of homeless people", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        userProcessContainer.remove(this);
        
        //re-populate
        Component[] component=userProcessContainer.getComponents();
        Component previous=component[component.length-1];
        DataTeamWorkAreaJPanel manageproduct=(DataTeamWorkAreaJPanel)previous;
        manageproduct.populateTable();  
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }
    }//GEN-LAST:event_btnAddActionPerformed
    
    private boolean validation(){
        if(txtLocation.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter the location", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtReason.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter the reason for homelessness", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtCount.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter no of people", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if((Integer)spinAge.getValue()<=-1 && (Integer)spinAgeTo.getValue()<=-1){
            JOptionPane.showMessageDialog(this, "Age should not be negative", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if((Integer)spinAge.getValue()>(Integer)spinAgeTo.getValue()){
            JOptionPane.showMessageDialog(this, "From age should be greater than to age", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtDisease.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter the chronic disease", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtFamilies.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter the number of families", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        //re-populate
        Component[] component=userProcessContainer.getComponents();
        Component previous=component[component.length-1];
        DataTeamWorkAreaJPanel manageproduct=(DataTeamWorkAreaJPanel)previous;
        manageproduct.populateTable();  
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAgeGroup;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblCreated;
    private javax.swing.JLabel lblDisease;
    private javax.swing.JLabel lblFamilies;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblReason;
    private javax.swing.JLabel lblTimestamp;
    private javax.swing.JLabel lblTo;
    private javax.swing.JSpinner spinAge;
    private javax.swing.JSpinner spinAgeTo;
    private javax.swing.JTextField txtCount;
    private javax.swing.JTextField txtDisease;
    private javax.swing.JTextField txtFamilies;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtModified;
    private javax.swing.JTextField txtReason;
    private javax.swing.JTextField txtTime;
    private javax.swing.JPanel workRequestPanel;
    // End of variables declaration//GEN-END:variables
}
